name: Unit Tests
description: Run Node.js unit tests

inputs:
  suit:
    description: Test suite to run
    required: true

runs:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash

    - run: npm run build
      shell: bash

    - shell: bash
      env:
        SUIT: ${{ inputs.suit }}
      run: |
        if [[ "${SUIT}" != "vitest" && "${SUIT}" != "mocha" ]]; then
          echo "Invalid suite: ${SUIT}" >&2
          exit 1
        fi

        npm run "test:unit:${SUIT}"
