name: Unit Tests
description: Run Node.js unit tests

runs:
  using: "composite"
  steps:
    - run: sudo apt-get install -y libunwind-dev
      shell: bash
    - run: npm install
      shell: bash
    - run: npm run build
      shell: bash
    - run: npm run test:unit:coverage
      shell: bash
    - run: npm run codecov
      shell: bash
