name: Unit Tests
description: Run Node.js unit tests

inputs:
  suit:
    description: Test suite to run
    required: true

runs:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash

    - run: npm run build
      shell: bash

    - run: npm run test:unit:${{ inputs.suit }}
      shell: bash
