name: Unit Tests
description: Run Node.js unit tests

runs:
  using: "composite"
  steps:
    - run: npm install
      shell: bash
    - run: npm run build
      shell: bash
    - run: NODE_OPTIONS=--max_old_space_size=4096 npm run test:unit:coverage
      shell: bash
    - run: npm run codecov
      shell: bash
