################################################################################
# Plugin development build image
################################################################################
FROM node:12.16.3-stretch-slim as plugin-dev-build

ADD ./bin /var/app/bin
ADD ./config /var/app/config
ADD ./docker-compose /var/app/docker-compose

ADD ./lib /var/app/lib

ADD ./plugins/available/kuzzle-plugin-auth-passport-local /var/app/plugins/available/kuzzle-plugin-auth-passport-local
# @todo remove when cluster is integrated
ADD ./plugins/available/kuzzle-plugin-cluster /var/app/plugins/available/kuzzle-plugin-cluster
ADD ./plugins/available/kuzzle-plugin-logger /var/app/plugins/available/kuzzle-plugin-logger
ADD ./plugins/enabled /var/app/plugins/enabled

ADD ./package.json /var/app/package.json
ADD ./package-lock.json /var/app/package-lock.json
ADD ./default.config.js /var/app/default.config.js

WORKDIR /var/app

RUN  set -x \
  && apt-get update && apt-get install -y \
       curl \
       python \
       make \
       g++ \
       python \
       libzmq3-dev \
  && npm set progress=false \
  && npm install -g --unsafe-perm --production \
    nodemon \
    kourou \
  && curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | sh -s -- -b /usr/local/bin \
  && rm -rf /var/lib/apt/lists/* \

  && npm install --production --unsafe-perm \
  && for plugin in plugins/enabled/*; do cd "$plugin"; npm install --production --unsafe-perm; cd /var/app; done \
  && for plugin in plugins/available/*; do cd "$plugin"; npm install --production -unsafe-perm; cd /var/app; done \

# Cleaning
  &&  /usr/local/bin/node-prune \
  && for plugin in plugins/enabled/*; do cd "$plugin"; /usr/local/bin/node-prune; cd /var/app; done \
  && for plugin in plugins/available/*; do cd "$plugin"; /usr/local/bin/node-prune; cd /var/app; done \
  && rm /usr/local/bin/node-prune \

  && npm prune --production \
  && for plugin in plugins/enabled/*; do cd "$plugin"; npm prune --production; cd /var/app; done \
  && for plugin in plugins/available/*; do cd "$plugin"; npm prune --production; cd /var/app; done \

  && for plugin in plugins/enabled/*; do cd "$plugin"; rm -rf .git/; cd /var/app; done \
  && for plugin in plugins/available/*; do cd "$plugin"; rm -rf .git/; cd /var/app; done \

  && strip node_modules/re2/build/Release/re2.node \
  && strip node_modules/re2/build/Release/obj.target/re2.node \

  && find / \( -name "*.md" -o -name "*.txt" -o -name "*.o" \) | xargs rm \

  && tar cfJ /system.tar.xz /lib /usr /var/app

################################################################################
# Plugin development image
################################################################################
FROM debian:stretch-slim as plugin-dev

LABEL io.kuzzle.vendor="Kuzzle <support@kuzzle.io>"
LABEL description="Develop new plugin or protocol for Kuzzle with ease"

COPY --from=plugin-dev-build /var/app/docker-compose/scripts/prepare.sh /bin/prepare
COPY --from=plugin-dev-build /var/app/docker-compose/scripts/run-plugin.sh /bin/run-plugin
COPY --from=plugin-dev-build /system.tar.xz /system/system.tar.xz
COPY --from=plugin-dev-build /usr/bin/xz /bin/xz

RUN  chmod a+x /bin/prepare \
  && chmod a+x /bin/run-plugin