sonar.organization=kuzzleio
sonar.projectKey=kuzzleio_kuzzle

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=./lib
sonar.tests=./test

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Coverage exclusions
sonar.coverage.exclusions=**/*.ts,**/*.vue

sonar.cpd.exclusions=lib/api/httpRoutes.js
