version: '3.4'

x-kuzzle-config: &kuzzle-config
  image: kuzzleio/kuzzle-runner:${NODE_VERSION:-16}
  command: > 
    bash -c "
      node ./docker/scripts/start-kuzzle-test.js --enable-plugins kuzzle-plugin-cluster,functional-test-plugin
    "
  volumes:
    - "..:/var/app"
  cap_add:
    - SYS_PTRACE
  ulimits:
    nofile: 65536
  sysctls:
    - net.core.somaxconn=8192
  depends_on:
    - redis
    - elasticsearch
  environment:
    - kuzzle_services__storageEngine__client__node=http://elasticsearch:9200
    - kuzzle_services__storageEngine__commonMapping__dynamic=true
    - kuzzle_services__internalCache__node__host=redis
    - kuzzle_services__memoryStorage__node__host=redis
    - kuzzle_server__protocols__mqtt__enabled=true
    - kuzzle_server__protocols__mqtt__developmentMode=false
    - kuzzle_http__accessControlAllowOrigin=localhost
    - kuzzle_limits__loginsPerSecond=50
    - kuzzle_server__protocols__http__additionalContentTypes=*json:["application/x-yaml"]
    - NODE_ENV=development
    - NODE_VERSION=${NODE_VERSION:-}
    - DEBUG=none
    - SECRETS_FILE_PREFIX=/var/app/
    # cluster
    - kuzzle_plugins__cluster__privileged=true
    - kuzzle_plugins__cluster__minimumNodes=3

services:
  nginx:
    image: nginx:1.19-alpine
    container_name: kuzzle_nginx
    depends_on:
      - kuzzle_node_1
      - kuzzle_node_2
      - kuzzle_node_3
    ports:
      - "7512:7512"
    volumes:
      - ../docker/nginx-dev:/etc/nginx/conf.d

  kuzzle_node_1:
    <<: *kuzzle-config
    container_name: kuzzle_node_1
    ports:
      - "17510:7512"
      - "1883:1883"

  kuzzle_node_2:
    <<: *kuzzle-config
    container_name: kuzzle_node_2
    ports:
      - "17511:7512"

  kuzzle_node_3:
    <<: *kuzzle-config
    container_name: kuzzle_node_3
    ports:
      - "17512:7512"

  redis:
    image: redis:6
    container_name: kuzzle_redis

  elasticsearch:
    image: kuzzleio/elasticsearch:7
    container_name: kuzzle_elasticsearch
    ulimits:
      nofile: 65536
