version: '3'

services:
  kuzzle:
    image: kuzzleio/core-dev:2
    command: sh -c 'chmod 755 /run.sh && /run.sh'
    volumes:
      - "..:/var/app"
      - "./scripts/run-test.sh:/run.sh"
      - "./config/pm2.json:/config/pm2.json"
    cap_add:
      - SYS_PTRACE
    ulimits:
      nofile: 65536
    sysctls:
      - net.core.somaxconn=8192
    ports:
      - "7512:7512"
    depends_on:
      - redis
      - elasticsearch
    environment:
      - kuzzle_services__storageEngine__client__node=http://elasticsearch:9200
      - kuzzle_services__storageEngine__commonMapping__dynamic=true
      - kuzzle_services__storageEngine__internalIndex__collections__users__dynamic=true
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_limits__loginsPerSecond=50
      - kuzzle_server__protocols__mqtt__enabled=true
      - kuzzle_server__protocols__mqtt__developmentMode=false
      - NODE_ENV=production
      - DEBUG
      - KUZZLE_SECRETS_FILE=/var/app/features-sdk/fixtures/secrets.enc.json
      - KUZZLE_VAULT_KEY=secret-password
      # Travis env var must be propagated into the container
      - TRAVIS
      - TRAVIS_COMMIT
      - TRAVIS_JOB_NUMBER
      - TRAVIS_BRANCH
      - TRAVIS_JOB_ID
      - TRAVIS_PULL_REQUEST
      - TRAVIS_REPO_SLUG

  redis:
    image: redis:5

  elasticsearch:
    image: kuzzleio/elasticsearch:7.4.0
    ulimits:
      nofile: 65536
