version: '3'

services:
  kuzzle:
    image: kuzzleio/core-dev-aarch64:2.x
    command: sh -c 'chmod 755 /run.sh && /run.sh'
    volumes:
      - "..:/var/app"
      - "./scripts/run-test-arm.sh:/run.sh"
      - "./config/pm2.json:/config/pm2.json"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - redis
      - elasticsearch
    environment:
      - kuzzle_services__storageEngine__client__node=http://elasticsearch:9200
      - kuzzle_services__storageEngine__commonMapping__dynamic=true
      - kuzzle_services__storageEngine__internalIndex__collections__users__dynamic=true
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_server__protocols__mqtt__enabled=true
      - kuzzle_server__protocols__mqtt__developmentMode=false
      - NODE_ENV=production
      - DEBUG=
      - CUCUMBER_EMBEDDED_HOST=localhost
      - NODE_LTS=${NODE_LTS:-10}
      # Travis env var must be propagated into the container
      - TRAVIS
      - TRAVIS_COMMIT
      - TRAVIS_JOB_NUMBER
      - TRAVIS_BRANCH
      - TRAVIS_JOB_ID
      - TRAVIS_PULL_REQUEST
      - TRAVIS_REPO_SLUG

  redis:
    image: redis:${REDIS_VERSION:-5}

  elasticsearch:
    image: kuzzleio/elasticsearch:7.3.0
    ulimits:
      nofile: 65536
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=alyx
      - cluster.name=kuzzle
      - discovery.type=single-node
