name: Cache Node Modules
description: Cache Node Modules

inputs:
  node-version:
    description: node version
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules-1.0.0
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ inputs.node-version }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ inputs.node-version }}-${{ hashFiles('package-lock.json') }}


