version: '3.4'

x-kuzzle-volumes: &kuzzle-volumes
  - "..:/var/app"
  - "./scripts/run-dev.sh:/run-dev.sh"
  - "./fixtures:/fixtures"

x-kuzzle-environment: &kuzzle-environment
  - kuzzle_services__storageEngine__client__node=http://elasticsearch:9200
  - kuzzle_services__storageEngine__commonMapping__dynamic=true
  - kuzzle_services__internalCache__node__host=redis
  - kuzzle_services__memoryStorage__node__host=redis
  - kuzzle_server__protocols__mqtt__enabled=true
  - kuzzle_server__protocols__mqtt__developmentMode=false
  - kuzzle_limits__loginsPerSecond=50
  - NODE_ENV=${NODE_ENV:-development}
  - DEBUG=${DEBUG:-kuzzle:*,-kuzzle:entry-point:protocols:websocket}
  # - DEBUG=${DEBUG:-none}
  - DEBUG_DEPTH=${DEBUG_DEPTH:-0}
  - DEBUG_MAX_ARRAY_LENGTH=${DEBUG_MAX_ARRAY:-100}
  - DEBUG_EXPAND=${DEBUG_EXPAND:-off}
  - DEBUG_SHOW_HIDDEN={$DEBUG_SHOW_HIDDEN:-on}
  - DEBUG_COLORS=${DEBUG_COLORS:-on}
  - KUZZLE_VAULT_KEY=${KUZZLE_VAULT_KEY:-secret-password}
  - KUZZLE_SECRETS_FILE=${KUZZLE_SECRETS_FILE:-/var/app/features-sdk/fixtures/secrets.enc.json}
  # Variables used by the development scripts
  - NODE_12_VERSION=12.13.0
  - WITHOUT_KUZZLE # Run only Elasticsearch and Redis
  - REBUILD # Force a rebuild of npm modules
  # cluster
  - kuzzle_plugins__cluster__privileged=true
  - KUZZLE_PLUGINS=kuzzle-plugin-cluster

services:
  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - kuzzle
    ports:
      - "7443:7443"
    volumes:
      - ./docker-compose/nginx:/etc/nginx/conf.d

  kuzzle:
    image: kuzzleio/core-dev:2
    command: sh -c 'chmod 755 /run-dev.sh && /run-dev.sh'
    volumes: *kuzzle-volumes
    cap_add:
      - SYS_PTRACE
    ulimits:
      nofile: 65536
    sysctls:
      - net.core.somaxconn=8192
    depends_on:
      - redis
      - elasticsearch
    ports:
      - "7512:7512"
      - "1883:1883"
      - "9229:9229"
      - "7510:7510"
      - "7511:7511"
    environment: *kuzzle-environment

  kuzzle_node:
    image: kuzzleio/core-dev:2
    command: sh -c 'chmod 755 /run-dev.sh && /run-dev.sh'
    volumes: *kuzzle-volumes
    cap_add:
      - SYS_PTRACE
    ulimits:
      nofile: 65536
    sysctls:
      - net.core.somaxconn=8192
    depends_on:
      - redis
      - elasticsearch
    ports:
      - "6512:7512"
      - "6510:7510"
      - "6511:7511"
    environment: *kuzzle-environment

  redis:
    image: redis:5
    ports:
      - "6379:6379"

  elasticsearch:
    image: kuzzleio/elasticsearch:7
    ports:
      - "9200:9200"
    ulimits:
      nofile: 65536
