module.exports = {
  'data:beforeCreate': ['write:add', 'publish:add'],
  'data:beforeCreateOrReplace': ['write:add', 'publish:add'],
  'data:beforeReplace': ['write:add', 'publish:add'],
  'data:beforeUpdate': ['write:add'],
  'data:beforeDelete': ['write:add', 'publish:add'],
  'data:beforeDeleteByQuery': ['write:add'],
  'data:beforeBulkImport': ['write:add'],
  'data:beforeUpdateMapping': ['write:add'],
  'data:beforeCreateCollection': ['write:add'],
  'data:beforeTruncateCollection': ['write:add'],
  'data:beforeCreateIndex': ['write:add'],
  'data:beforeDeleteIndex': ['write:add'],
  'data:beforeDeleteIndexes': ['write:add'],
  'data:beforeRefreshIndex': ['write:add'],
  'data:beforeSetAutoRefresh': ['write:add'],
  'data:beforeGetAutoRefresh': ['write:add'],
  'cleanDb:deleteIndexes': ['write:add'],
  'prepareDb:createInternalIndex': ['write:add'],
  'prepareDb:createFixturesIndex': ['write:add'],
  'prepareDb:updateMappingRoles': ['write:add'],
  'prepareDb:updateMappingProfiles': ['write:add'],
  'prepareDb:updateMappingUsers': ['write:add'],
  'prepareDb:importMapping': ['write:add'],
  'prepareDb:importFixtures': ['write:add']
};

