name: Cluster Monkey Tests
description: Run monkey tests on a Kuzzle Cluster
inputs:
  node-version:
    description: Node version to use in the Kuzzle Docker image
    required: true

runs:
  using: "composite"
  steps:
    - run: apt-get install -y libunwind-dev
      shell: bash
    - run: ./.ci/scripts/run-monkey-tests.sh
      env:
        NODE_VERSION: ${{ inputs.node-version }}
      shell: bash
