name: kuzzleio/elasticsearch

on:
  push:
    branches:
      - master

env:
  DOCKER_PLATFORMS: "linux/amd64,linux/arm64"
  ELASTICSEARCH_VERSION: "7.16.2"

jobs:
  build-and-push:
    name: Build and push elasticsearch image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./elasticsearch
          file: ./elasticsearch/Dockerfile
          push: true
          build-args: ELASTICSEARCH_VERSION=${{ env.ELASTICSEARCH_VERSION }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
          tags: kuzzleio/elasticsearch:${{ env.ELASTICSEARCH_VERSION }},kuzzleio/elasticsearch:7, kuzzleio/elasticsearch:latest
