name: Main branches push checks

on:
  push:
    branches:
      - master
      - 2-dev

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - uses: ./.github/actions/es-lint

  unit-tests:
    name: Unit Tests - Node.js v${{ matrix.node-version }}
    needs: ['lint']
    strategy:
      matrix:
        node-version: ['12.16', '12.18']
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/unit-tests

  functional-tests-legacy:
    name: Integration Tests Legacy - ${{ matrix.test_set }} - Node.js v${{ matrix.node-version }}
    needs: ['unit-tests']
    strategy:
      matrix:
        test_set: ['http', 'websocket', 'mqtt']
        node-version: ['12.16', '12.18']
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/functional-tests
        env:
          KUZZLE_FUNCTIONAL_TESTS: test:functional:legacy:${{ matrix.test_set }}
        with:
          docker-compose-test-file: ./.ci/test.yml

  functional-tests:
    name: Integration Tests SDK - ${{ matrix.test_set }} - Node.js v${{ matrix.node-version }}
    needs: ['unit-tests']
    strategy:
      matrix:
        test_set: ['http', 'websocket']
        node-version: ['12.16', '12.18']
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/functional-tests
        env:
          KUZZLE_FUNCTIONAL_TESTS: test:functional:sdk:${{ matrix.test_set }}
        with:
          docker-compose-test-file: ./.ci/test.yml

  functional-tests-cluster:
    name: Integration Tests - Cluster - Node.js v${{ matrix.node-version }}
    needs: ['unit-tests']
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: ['12.16', '12.18']
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cluster legacy tests
        run: ./.ci/scripts/run-test-cluster.sh
          
  error-codes-check:
    name: Documentation - Error codes check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm install
      - name: Test error codes
        run: ./.ci/scripts/check-error-codes-documentation.sh

  documentation-production:
    name: Deploy Documentation to production
    if: github.ref == 'ref/head/master'
    needs: ['functional-tests-legacy', 'functional-tests', 'functional-tests-cluster']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.cache/pip
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: ./.github/actions/deploy-doc
        with:
          REGION: us-west-2
          S3_BUCKET: docs.kuzzle.io
          CLOUDFRONT_ID: E3D6RP0POLCJMM
          FRAMEWORK_BRANCH: master

  documentation-staging:
    name: Deploy Documentation to staging
    if: github.ref == 'ref/head/2-dev'
    needs: ['functional-tests-legacy', 'functional-tests', 'functional-tests-cluster']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.cache/pip
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: ./.github/actions/deploy-doc
        with:
          REGION: us-west-2
          S3_BUCKET: docs-next.kuzzle.io
          CLOUDFRONT_ID: E2ZCCEK9GRB49U
          FRAMEWORK_BRANCH: dev

  dockerhub-deploy:
    name: Build and deploy images to Dockerhub
    needs: ['functional-tests-legacy', 'functional-tests', 'functional-tests-cluster']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.cache/pip
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Get branch name
        # Github expose branch name with this format '/ref/branch/branchName'
        # So we need to extract the wanted part (branchName)
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: ./.github/actions/dockerhub
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          BRANCH: ${{ steps.extract_branch.outputs.branch }}

  npm-deploy:
    name: Build and deploy images to Dockerhub
    needs: ['functional-tests-legacy', 'functional-tests', 'functional-tests-cluster']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.cache/pip
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: ./.github/actions/npmjs
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}